# Generated by Django 4.0.6 on 2022-07-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
    ]
