# Generated by Django 4.0.6 on 2022-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='< Описания пока нет, но в скором времени появится >'),
        ),
    ]
